Repository ngx-rocket/generator-ngx-rocket, pull requests merged in 2018-02, with the labels that each got.

#239 Fixed missing material module imports (fixes #236)
  generators/app/templates/src/app/__material.material.module.ts
Labels: bug

#240 Update angular style guide links
  README.md
  generators/app/templates/docs/coding-guides/__ionic.ionic.md
  generators/app/templates/docs/coding-guides/angular.md
  generators/app/templates/docs/coding-guides/html.md
  generators/app/templates/docs/coding-guides/typescript.md
Labels: documentation

#241 ionic: invalid view to insert when route to lazy loading page
  generators/app/templates/src/app/core/shell/__ionic._shell.component.ts
Labels: bug

#237 BREAKING CHANGE: Switch to new HttpClient API (closes #94)
  generators/app/templates/src/app/_app.component.spec.ts
  generators/app/templates/src/app/_app.module.ts
  generators/app/templates/src/app/core/_core.module.ts
  generators/app/templates/src/app/core/_index.ts
  generators/app/templates/src/app/core/http/api-prefix.interceptor.spec.ts
  generators/app/templates/src/app/core/http/api-prefix.interceptor.ts
  generators/app/templates/src/app/core/http/cache.interceptor.spec.ts
  generators/app/templates/src/app/core/http/cache.interceptor.ts
  generators/app/templates/src/app/core/http/error-handler.interceptor.spec.ts
  generators/app/templates/src/app/core/http/error-handler.interceptor.ts
  generators/app/templates/src/app/core/http/http-cache.service.spec.ts
  generators/app/templates/src/app/core/http/http-cache.service.ts
  generators/app/templates/src/app/core/http/http.service.spec.ts
  generators/app/templates/src/app/core/http/http.service.ts
  generators/app/templates/src/app/core/http/request-options-args.ts
  generators/app/templates/src/app/home/_home.component.spec.ts
  generators/app/templates/src/app/home/quote.service.spec.ts
  generators/app/templates/src/app/home/quote.service.ts
Labels: feature

#242 Feature/Strict mode compatibility
  generators/app/templates/src/app/core/route-reusable-strategy.ts
Labels: feature

#246 Feature/no ui library
  generators/app/index.js
  generators/app/options.json
  generators/app/templates/src/_main.scss
  generators/app/templates/src/app/about/__raw.about.component.html
  generators/app/templates/src/app/about/_about.component.scss
  generators/app/templates/src/app/core/_core.module.ts
  generators/app/templates/src/app/core/shell/__raw.shell.component.html
  generators/app/templates/src/app/core/shell/_shell.component.scss
  generators/app/templates/src/app/core/shell/header/__raw._header.component.html
  generators/app/templates/src/app/core/shell/header/__raw._header.component.spec.ts
  generators/app/templates/src/app/core/shell/header/__raw._header.component.ts
  generators/app/templates/src/app/core/shell/header/__raw.header.component.scss
  generators/app/templates/src/app/home/__raw.home.component.html
  generators/app/templates/src/app/home/_home.component.scss
  generators/app/templates/src/app/login/__auth+raw.login.component.html
  generators/app/templates/src/app/login/__auth+raw.login.component.scss
  generators/app/templates/src/app/shared/loader/__raw.loader.component.html
  generators/app/templates/src/app/shared/loader/_loader.component.scss
  generators/app/templates/src/theme/__raw.theme-variables.scss
  generators/app/templates/src/theme/_theme.scss
  scripts/tests/app/web/raw-authentication.json
  scripts/tests/app/web/raw.json
Labels: feature

#245 Feature/tests lazy
  generators/app/prompts.js
  scripts/tests/app/cordova/bootstrap-authentication.json
  scripts/tests/app/cordova/bootstrap.json
  scripts/tests/app/cordova/ionic-authentication.json
  scripts/tests/app/cordova/ionic.json
  scripts/tests/app/cordova/material-authentication.json
  scripts/tests/app/cordova/material.json
  scripts/tests/app/web+cordova/bootstrap-authentication.json
  scripts/tests/app/web+cordova/ionic-authentication.json
  scripts/tests/app/web+cordova/material-authentication.json
  scripts/tests/app/web/bootstrap-authentication.json
  scripts/tests/app/web/bootstrap.json
  scripts/tests/app/web/ionic-authentication.json
  scripts/tests/app/web/ionic.json
  scripts/tests/app/web/material-authentication.json
  scripts/tests/app/web/material.json
Labels: chore

#247 Chore/update dependencies
  generators/app/templates/_package.json
  package-lock.json
  package.json
Labels: chore

#251 Added script to serve app with service worker (closes #250)
  generators/app/templates/_README.md
  generators/app/templates/_package.json
Labels: feature

#252 Added missing tests in CI
  .travis.yml
  README.md
  appveyor.yml
  generators/app/templates/.stylelintrc
  generators/app/templates/_README.md
  generators/app/templates/_package.json
  generators/app/templates/src/app/about/__raw.about.component.html
  generators/app/templates/src/app/core/shell/__raw.shell.component.ts
  generators/app/templates/src/app/core/shell/header/__raw._header.component.ts
  generators/app/templates/src/app/login/__auth+raw.login.component.scss
  generators/app/templates/src/app/shared/loader/_loader.component.scss
  generators/app/templates/src/theme/_theme.scss
Labels: chore
