Repository ngx-rocket/generator-ngx-rocket, pull requests merged in 2018-08, with the labels that each got.

#357 Updated angular guide with a FAQ section and added NGXS references
  generators/app/templates/docs/coding-guides/angular.md
Labels: documentation

#365 Update _index.html, fix cordova routing bug
  generators/app/templates/src/_index.html
Labels: bug

#364 Add CircleCI config to build Cordova/Android paths
  .circleci/config.yml
  .editorconfig
  README.md
  generators/app/templates/__cordova._config.xml
  scripts/test.sh
Labels: feature

#361 Add ionic tabs after shell integration as component
  generators/app/index.js
  generators/app/prompts.js
  generators/app/templates/src/app/_app.module.ts
  generators/app/templates/src/app/settings/__ionic-tabs._settings-routing.module.ts
  generators/app/templates/src/app/settings/__ionic-tabs._settings.component.html
  generators/app/templates/src/app/settings/__ionic-tabs._settings.component.scss
  generators/app/templates/src/app/settings/__ionic-tabs._settings.component.spec.ts
  generators/app/templates/src/app/settings/__ionic-tabs._settings.component.ts
  generators/app/templates/src/app/settings/__ionic-tabs._settings.module.ts
  generators/app/templates/src/app/shell/__ionic-side-menu._shell.component.html
  generators/app/templates/src/app/shell/__ionic-side-menu._shell.component.ts
  generators/app/templates/src/app/shell/__ionic-tabs.shell.component.html
  generators/app/templates/src/app/shell/__ionic-tabs.shell.component.ts
  generators/app/templates/src/app/shell/_shell.component.scss
  generators/app/templates/src/app/shell/_shell.component.spec.ts
  generators/app/templates/src/translations/_en-US.json
  generators/app/templates/src/translations/_fr-FR.json
  scripts/tests/app/cordova/ionic-authentication.json
  scripts/tests/app/cordova/ionic.json
  scripts/tests/app/web+cordova/ionic-authentication.json
  scripts/tests/app/web/ionic-authentication.json
  scripts/tests/app/web/ionic.json
Labels: feature
